services:
  php:
    build: 
      context: .
    ports:
      - "8101:8101"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - external

  mysql:
    image: mysql:8.0-oracle
    container_name: TP_php
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
    networks:
      - external

networks:
  external:
    driver: bridge